# Generated by Django 5.2.5 on 2025-08-21 13:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('created_At', models.DateTimeField(default=datetime.datetime.now)),
                ('unique_id', models.CharField(auto_created='', blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_code.document')),
            ],
        ),
    ]
