# Generated by Django 5.2.5 on 2025-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='inputs/input.pdf', upload_to='inputs/'),
        ),
        migrations.AddField(
            model_name='scan',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
